---
title: "LimnoSat-US_Tutorial"
author: "Simon Topp"
date: "11/2/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---




```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(leaflet)
library(sf)
library(feather)
library(lubridate)
library(mapview)
library(USAboundaries)
library(s2)
library(elevatr)
library(trend)
library(tsibble)
library(imputeTS)
library(ggthemes)
library(nhdplusTools)
library(tmap)
library(raster)
library(caret)
library(rpart)
library(yardstick)
library(rpart.plot)
library(patchwork)
library(cowplot)
library(lfstat) #for water_year function
library(zyp) #for zyp::zyp.sen, getting intercept for plotting sens slopes

# Use dplyr select
select<-dplyr::select


sf_use_s2(use_s2 = T)
knitr::opts_chunk$set(echo = TRUE, warning = F, comment = F, message = F)
```


## Trend Analysis

### Trend Data prep

Lots of key decisions in here. Could iterate


```{r, eval = F}



co_summary <- ls_co %>%
  dplyr::select(-year, -sat) %>%
  mutate(month = month(date),
         year = year(date),
         doy = yday(date)) %>%
  filter(month %in% 7:9, 
         doy <= 258) %>% #Sept 14/15
  group_by(Hylak_id,year) %>%
  add_count() %>%
  filter(year >= 1984) %>% #changed to >= so we don't drop 1984... 
  filter(n >= 3) %>% # at least 3 observations per year
  group_by(Hylak_id) %>%
  mutate(unique_years = n_distinct(year)) %>%
  filter(unique_years > 30) %>% # at least 30 years of data
  arrange(year) %>%
  #complete years
  group_by(Hylak_id,year) %>%
  summarize(across(c(Blue:dWL),
                   .fns = list(mean = mean,
                               sd = sd,
                               max = max,
                               min = min,
                               median = median), na.rm = T,
                   .names = "{.col}-{.fn}"))%>%
  ungroup() %>%
  as_tsibble(., key = Hylak_id, index=year) %>% #time series tibble
  fill_gaps() %>% #imputing, though not sure what's going on under the hood
  as_tibble() %>%
  pivot_longer(cols = `Blue-mean`:`dWL-median`,
               names_to = c('var','stat'),
               names_sep = '-') %>%
  group_by(Hylak_id, var, stat) %>%
  arrange(year) %>%
  mutate(impute_value = na_interpolation(value, maxgap = 1))


filled_enough <- co_summary %>%
  group_by(Hylak_id) %>%
  summarize(any_nas = any(is.na(impute_value))) %>% # check if there are missing values in each Hylak_id timeseries
  filter(any_nas == F) # only select the sites with a max of 1 year of missing data


co_full <- co_summary %>%
  filter(Hylak_id %in% filled_enough$Hylak_id) 

#How many lakes? 
length(unique(co_full$Hylak_id))

save(co_full, file = 'data/color_summary.RData')
```


## PRISM

#### Get lat/long for PRISM
```{r, eval=F}
#Extract lat/long for PRISM
dwl_all_ungrouped<-dwl_all%>%ungroup()%>%select(Hylak_id, geometry) 

separated_coord <- dwl_all_ungrouped %>%
    mutate(lat = unlist(map(dwl_all_ungrouped$geometry,2)),
           long = unlist(map(dwl_all_ungrouped$geometry,1))) %>%
  select(-geometry) %>%
  distinct() %>%
  relocate(Hylak_id, .after = last_col())

#PRISM can only pull 500 sites at a time, so split into two dataframes
separated_coord_1<-separated_coord %>%
  slice(1:500)
separated_coord_2<-separated_coord %>%
  slice(501:nrow(.))
# write_csv(separated_coord_1, "data/prism/separated_coord_1.csv", col_names = FALSE)
# write_csv(separated_coord_2, "data/prism/separated_coord_2.csv",col_names = FALSE)
# Use the above .csv files to download PRISM data for each individual lakes
# https://prism.oregonstate.edu/explorer/bulk.php 
```

#### Read in PRISM data
```{r}

dir<-here("data/prism/download")
files<-list.files(dir)
prism<-data.frame() # data frame to store all prism data
for(i in 1:length(files)){ # loops over all files in prism/download directory
  cur<-read.table(file.path(dir,paste(files[i],sep='')),
                  header=T,sep=",",skip=10,
                  stringsAsFactors = F) # read in all prism files
  cur$fileName<-files[i]
  #keep track of which .csv file data came from to make sure it's all there
  prism<-rbind(prism,cur)
}
prism<-prism %>%
    rename(ppt_mm=`ppt..mm.`,
           tmean_degC=`tmean..degrees.C.`,
           elev_m_prism=`Elevation..m.`,
           Hylak_id=Name,
           lon_dec_deg=Longitude,
           lat_dec_deg=Latitude,
           date=Date)%>%
  mutate(date=ym(date)) 
  # select(-fileName)

# Double check that all files joined
# length(unique(prism$fileName))

#Double check to make sure all data are there
# str(prism)


```

### Summary stats
```{r}


# Summary statistics by site
prism_sum <- prism %>%
  select(-c(lat_dec_deg, lon_dec_deg, elev_m_prism, fileName)) %>%
  pivot_longer(-c(Hylak_id, date)) %>%
  mutate(
    year = year(date),
    water_year = water_year(date, "usgs"),
    #uses the USGS standard of Oct
    month = month(date),
    season = case_when(
      year == water_year & month %in% c(3, 4, 5) ~ "spring",
      year == water_year &
        month %in% c(6, 7, 8) ~ "summer",
      year == water_year &
        month %in% c(1, 2) ~ "winter",
      year != water_year &
        month %in% c(12) ~ "winter"
    ),
    # Hylak_id=as.factor(as.integer(Hylak_id)),
    water_year = as.numeric(as.character(water_year))
  ) %>%
  drop_na(season) %>%
  group_by(Hylak_id, water_year, season, name) %>%
  summarize(mean = mean(value, na.rm = TRUE))

prism_sum_ppt <- prism_sum %>%
  filter(name == "ppt_mm")
prism_sum_temp <- prism_sum %>%
  filter(name == "tmean_degC")

##########################################################################################
##Functions for calculating sens slopes and intercepts for plotting later
##########################################################################################
map_sens2 <- function(df) {
  sens.slope(df$mean)
}


sens_slope <- function(mod) {
  mod$estimate[[1]]
}

#https://kevintshoemaker.github.io/NRES-746/TimeSeries_all.html
#For getting sens intercept, helpful for plotting later
map_zyp <- function(df) {
  zyp::zyp.sen(mean ~ water_year, df)
  # sens.slope(df$mean)
}


sens_intercept <- function(mod) {
  mod$coefficients[[1]] # pull out y-int estimate for ploting
}


#Coefficient of variation -- how variation is temp and precip over time?
cv <- function(df)  {
  sd(df$mean) / mean(df$mean)
}

## Precipitation first---
## Only keeping these separate for the trend categories.
prism_sum_ppt_nested <- prism_sum_ppt %>%
  group_by(Hylak_id, season, name) %>%
  nest() %>%
  mutate(
    sens = map(data, map_sens2),
    sens_sum = map(sens, broom::glance),
    slope = map(sens, sens_slope),
    zyp_mod = map(data, map_zyp),
    cv = map(data, cv),
    intercept = map(zyp_mod, sens_intercept)
  )

prism_sum_temp_nested <- prism_sum_temp %>%
  group_by(Hylak_id, season, name) %>%
  nest() %>%
  mutate(
    sens = map(data, map_sens2),
    sens_sum = map(sens, broom::glance),
    slope = map(sens, sens_slope),
    zyp_mod = map(data, map_zyp),
    cv = map(data, cv),
    intercept = map(zyp_mod, sens_intercept)
  )

## Un-nest PPT
prism_sum_ppt_unnested = unnest(prism_sum_ppt_nested, c(sens_sum, slope, season, name)) %>%
  mutate(
    Trend_ppt = case_when(
      p.value <= 0.05 & slope >= 0 ~ 'wetter',
      p.value <= 0.05 & slope <= 0 ~ 'drier',
      p.value > 0.05 ~ 'No trend'
    ),
    Trend_ppt = factor(Trend_ppt,
                       levels = c('No trend',
                                  'wetter',
                                  'drier'))
  )
## Un-nest TEMP
prism_sum_temp_unnested = unnest(prism_sum_temp_nested, c(sens_sum, slope, season, name)) %>%
  mutate(
    Trend_temp = case_when(
      p.value <= 0.05 & slope >= 0 ~ 'warmer',
      p.value <= 0.05 &
        slope <= 0 ~ 'cooler',
      p.value > 0.05 ~ 'No trend'
    ),
    Trend_temp = factor(Trend_temp,
                        levels = c('No trend',
                                   'warmer',
                                   'cooler'))
  )

#Extract all covariates for modeling...
prism_ppt_trends_wide <- prism_sum_ppt_unnested %>%
  select(Hylak_id, season, name, cv, slope) %>%
  unnest(c(cv, slope)) %>%
  pivot_wider(names_from = c("season", "name"),
              values_from = c("slope", "cv"))

prism_temp_trends_wide <- prism_sum_temp_unnested %>%
  select(Hylak_id, season, name, cv, slope) %>%
  unnest(c(cv, slope)) %>%
  pivot_wider(names_from = c("season", "name"),
              values_from = c("slope", "cv"))


##Dataframe with all the actual slopes and cv values
prism_trends_wide <-
  inner_join(prism_ppt_trends_wide, prism_temp_trends_wide)

##Data with all the ppt and temp trend categories
ppt_trend_categories <- prism_sum_ppt_unnested %>%
  select(Hylak_id, Trend_ppt) %>%
  pivot_wider(
    names_from = c("season"),
    values_from = c("Trend_ppt"),
    names_prefix = "ppt_trend_"
  ) %>%
  ungroup() %>%
  select(-name)
temp_trend_categories <- prism_sum_temp_unnested %>%
  select(Hylak_id, Trend_temp) %>%
  pivot_wider(
    names_from = c("season"),
    values_from = c("Trend_temp"),
    names_prefix = "temp_trend_"
  ) %>%
  ungroup() %>%
  select(-name)

prism_trend_categories <-
  inner_join(ppt_trend_categories, temp_trend_categories)
```

#### Interrogate trends
```{r}

#How many lakes are getting wetter/drier in each season?
prism_sum_ppt_unnested %>%
  unnest(data) %>%
  ungroup() %>%
  mutate(n_lakes_total = length(unique(Hylak_id))) %>%
  group_by(Trend_ppt, season, n_lakes_total) %>%
  summarize(n_trending = length(unique(Hylak_id))) %>%
  mutate(perc = (n_trending / sum(n_lakes_total)) * 100,
         perc = round(perc, 1))

#How many lakes are getting warmer/cooler in each season?
prism_sum_temp_unnested %>%
  unnest(data) %>%
  ungroup() %>%
  mutate(n_lakes_total = length(unique(Hylak_id))) %>%
  group_by(Trend_temp, season, n_lakes_total) %>%
  summarize(n_trending = length(unique(Hylak_id))) %>%
  mutate(perc = (n_trending / sum(n_lakes_total)) * 100,
         perc = round(perc, 1)) 

```

## Human populations trends
```{r}
load("data/glcp_sub.RData")
population_trends <-  glcp_high_lakes %>%
  select(Hylak_id, year, pop_sum) %>%
  drop_na() %>%
  pivot_wider(names_from = "year",
              values_from = "pop_sum",
              names_prefix = "pop_year_") %>%
  group_by(Hylak_id) %>%
  summarize(population_change = ((pop_year_2015 - pop_year_1995) / pop_year_1995) *
              100)

```


## Net Trends in DWL


```{r}

load('data/ls_elev.RData')
load('data/color_summary.RData')
load('data/nhd_lakes.RData')


nhd_hylak <- nhd_hylak %>%
  filter(elevation >= 1400) %>% ## changed to have the same cut off as in 2_GreenBlueMedians.Rmd?
  filter(ftype %in% c('LakePond', 'Reservoir'))

actually_high_lakes <- nhd_hylak


high_lakes <- co_full %>%
  filter(Hylak_id %in% actually_high_lakes$Hylak_id)

#How many lakes?
length(unique(high_lakes$Hylak_id))


map_sens <- function(df) {
  sens.slope(df$impute_value)
}


#https://kevintshoemaker.github.io/NRES-746/TimeSeries_all.html
#For getting sens intercept, helpful for plotting later
map_zyp <- function(df) {
  zyp::zyp.sen(impute_value ~ year, df)
}


sens_intercept <- function(mod) {
  mod$coefficients[[1]] # pull out y-int estimate for ploting
}


sens_est <- function(mod) {
  mod$estimates[[1]] #changed because others slope is a `named num` rather than numeric
  # mod$estimate
}

val_mean <- function(df) {
  early_mean <- df %>%
    filter(year < 2005) %>%
    pull(impute_value) %>%
    mean(., na.rm = T)
}

trend_plotter <- function(study_lakes = high_lakes,
                          v = 'dWL',
                          x = 'Dominant Wavelength Sens Slope') {
  trend_plot <- function(df) {
    ggplot(df, aes(x = year,
                   y = impute_value)) +
      geom_point() +
      stat_smooth(method = 'lm')
  }
  
  
  co_mods <- study_lakes %>%
    filter(var == v) %>%
    group_by(Hylak_id, stat) %>%
    nest() %>%
    mutate(
      sens = map(data, map_sens),
      plots = map(data, trend_plot),
      sens_sum = map(sens, broom::glance),
      slope = map(sens, sens_est),
      zyp_mod = map(data, map_zyp),
      intercept = map(zyp_mod, sens_intercept),
      early_mean = map(data, val_mean)
    )
  
  
  
  
  
  
  sens_sum = unnest(co_mods, c(sens_sum, slope, early_mean)) %>%
    mutate(
      Trend = case_when(
        p.value <= 0.05 & slope >= 0 & early_mean < 530 ~ 'Blue -> Green',
        p.value <= 0.05 &
          slope >= 0 &
          early_mean >= 530 ~ 'Intensifying Green/Yellow',
        #Added >= instead of > IAO 2022-01-25
        p.value <= 0.05 &
          slope <= 0 & early_mean > 530 ~ 'Green -> Blue',
        p.value <= 0.05 &
          slope <= 0 & early_mean < 530 ~ 'Intensifying Blue',
        p.value > 0.05 ~ 'No trend'
      ),
      Trend = factor(
        Trend,
        levels = c(
          'No trend',
          'Intensifying Blue',
          'Green -> Blue',
          'Intensifying Green/Yellow',
          'Blue -> Green'
        )
      )
    )
  
  
  plot <- ggplot(sens_sum %>%
                   dplyr::filter(stat != 'sd'),
                 aes(x = slope, color = Trend)) +
    geom_freqpoly(bins = 20, size = 1) +
    facet_wrap( ~ stat) +
    theme_few() +
    theme(legend.position = 'top',
          legend.direction = 'horizontal') +
    guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
    scale_color_manual(
      values = c('gray20', '#1f78b4', '#a6cee3', '#b2df8a', '#33a02c'),
      name = ''
    ) +
    xlab(x) +
    ylab('Lake count')
  
  
  return(list(sens_sum, plot))
}
```

## DWL modes

### DWL histogram


```{r}
high_lakes_descriptor <- glcp_high_lakes %>%
  group_by(Hylak_id) %>%
  summarize(across(where(is.numeric),mean))

 

high_modes <- high_lakes %>%
  filter(var == 'dWL',
         stat == 'median') %>%
  dplyr::mutate(decade = cut(year, breaks = c(1984,1996,2008,2021),
                             labels = c('1985-96','1997-2008','2009-2020'))) %>%
  group_by(Hylak_id, decade) %>%
  summarize(dWL = round(median(value, na.rm = T),0)) %>%
  ungroup() %>%
  inner_join(fui.lookup) %>%
  inner_join(fui.colors) 


bg.fui = tibble(
  ymin = c(470,475,480,485,489,495,509,530,549,559,564,567,568,569,570,573,575,577,579,581,583),
  ymax = c(475,480,485,489,495,509,530,549,559,564,567,568,569,570,573,575,577,579,581,583,590),
  color = c(
  "#2158bc", "#316dc5", "#327cbb", "#4b80a0", "#568f96", "#6d9298", "#698c86", 
  "#759e72", "#7ba654", "#7dae38", "#94b660","#94b660", "#a5bc76", "#aab86d", 
  "#adb55f", "#a8a965", "#ae9f5c", "#b3a053", "#af8a44", "#a46905", "#9f4d04")
)

##Legend only
legend<-ggplot() + 
  geom_rect(data = bg.fui, 
            aes(ymin = ymin, ymax = ymax, xmin = -5, xmax = 100, fill = color)) + 
  scale_fill_identity() + 
  theme_few() +
  scale_x_continuous(expand = c(0, 0))+
  scale_y_continuous(expand = c(0, 0))+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_text(size=5),
        axis.title.y=element_text(size=6),
        plot.title=element_text(size=6, hjust=-0.05))+
  labs(y="Dominant wavelength (nm)",
       title="Forel-Ule\ncolor")

# make prettier
# png(filename = 'figs/dwl_hist_three_periods.png', width = 4, height = 4,
#     units = 'in', res = 300)
# 
# 
# base<-ggplot() + 
#   facet_wrap(~decade, ncol = 1) + 
#   geom_rect(data = bg.fui, 
#             aes(xmin = ymin, xmax = ymax, ymin = -5, ymax = 100, fill = color)) + 
#   geom_vline(xintercept = 530, linetype = 3) +
#   geom_histogram(data = high_modes, aes(x=dWL, y = ..density..), fill = NA,
#                  color = 'black', alpha = .3, bins = 40) + 
#   geom_density(data = high_modes, aes(x=dWL)) + 
#   scale_x_continuous(expand = c(0, 0))+ #get rid of whitespace
#   scale_fill_identity() + 
#   theme_few() +
#   coord_cartesian(ylim = c(0,.03))  +
#   labs(x="Dominant wavelength (nm)",
#        y="Density")
# 
# base+inset_element(legend, 0.85, 0.75, 1, 1)
# 
# layout <- '
# A#
# AB
# A#
# '
# wrap_plots(A = base, B = legend, design = layout)+
#   plot_layout(widths = c(5, 0.5))
# 
# 
# dev.off()





```


## DWL Trends

```{r}
## Pull data for plotting
dWL_trends <- trend_plotter()


dwl <- dWL_trends[[1]] %>%
  inner_join(nhd_hylak, by = 'Hylak_id')

dwl_all <- dwl %>%
  filter(stat == 'median') %>%
  unnest(data) %>%
  unnest(intercept)


# set.seed(111)
# set.seed(1)
set.seed(999)
dwl_specials <- dwl_all %>%
  # filter(abs(slope) >= 1 | Trend == 'No trend') %>%
  # filter(p.value < 0.05 | Trend == 'No trend') %>% # Had to change from 0.001 to 0.05 to get a blue->green example lake
  filter(abs(slope) >= 1 &
           p.value < 0.05) %>% #I think it would be better to not show a trend line for "No Trend"
  group_by(Trend) %>%
  sample_n(1) %>%
  pull(Hylak_id)

full_spec <- dwl_all %>%
  filter(Hylak_id %in% dwl_specials)

#How many lakes in each trend category?
trend_labels <- dwl_all %>%
  group_by(Trend) %>%
  summarize(n = length(unique(Hylak_id))) %>%
  mutate(perc = (n / sum(n)) * 100,
         perc = round(perc, 0)) 



trendColors <- c(
  'No trend' = 'grey90',
  'Intensifying Blue' = '#1f78b4',
  'Green -> Blue' = '#a6cee3',
  'Intensifying Green/Yellow' = '#33a02c',
  'Blue -> Green' = '#b2df8a'
)


#Export
png(filename = 'figs/Trend Examples.png',
    width = 5,
    height = 8,
    res = 600,
    units = 'in')
ggplot(dwl_all, aes(x = year, y = value, group = Hylak_id)) +
  geom_abline(aes(intercept = intercept, slope = slope), color="grey50", size=0.1, alpha=0.5) + #background Sen's slopes
  geom_abline(data = full_spec, 
              aes(intercept = intercept, slope = slope, color=Trend),
              size=1) + #Sen's slope for selected sites
  geom_point(data = full_spec, aes(fill=Trend), shape=21) + 
  scale_fill_manual(values=trendColors)+
  scale_color_manual(values=trendColors)+
  geom_text(x = 1990, y = 585,
            aes(group=Trend, label = paste("n =",n)),
            color="black",
            data = trend_labels, size=3)+ #Add label for sample size
  scale_x_continuous(breaks=seq(1986, 2018, 6))+
  facet_wrap(~Trend, nrow=5) + 
  theme_few()+
  theme(legend.position="none",
        plot.margin = unit(c(0,0.2,0,0), "cm"),)+
  labs(y="Dominant wavelength (nm)",
       x="Year") +
  
  ggplot(dwl_all %>%
             distinct(Hylak_id,.keep_all = T),aes(x=slope,color=Trend)) + 
  geom_freqpoly(bins = 20, size = 1) + 
  geom_vline(xintercept=0, linetype="dashed", size=0.5)+
  facet_wrap(~Trend, nrow=5, scales="free_y") +
  theme_few() + 
  scale_y_continuous(position="right")+
  scale_x_continuous(breaks=seq(-1.5, 1.5, 1))+
  theme(legend.position="none",
        plot.margin = unit(c(0,0,0,0.2), "cm"),
        strip.text.x = element_text(color="white"), #Keep strips but color white so they are invisible
        legend.direction = 'horizontal') +
  scale_color_manual(values=trendColors)+
  xlab("Slope")+
  ylab('Lake count') + 
  plot_layout(widths = c(1, 0.6))
dev.off()

```



## DWL map

```{r}

load('data/spatial_data_analysis2.RData')

dwl_map <- dwl %>%
  filter(stat == 'median') %>%
  dplyr::select(Hylak_id,Trend) %>%
  inner_join(site_cols,.) %>%
  arrange(Trend)



png(filename = 'figs/trend_map.png',
    width = 4, height = 6, units = 'in', res = 300)

tm_shape(hil) +
  tm_raster(palette = gray(0:10 / 10), style = "cont", legend.show = FALSE) + 
tm_shape(ras) + 
  tm_raster(alpha = 0.4,
            style = 'cont',
            title = 'Elevation (m)',
            palette = 'Greys',
            legend.show = F) + 
tm_shape(states) + 
  tm_borders(lwd = 1,
             col = 'black') + 
tm_shape(dwl_map) + 
    tm_bubbles(size = .05,
             col = 'Trend',
             shape=21,
             border.col = 'black',
             border.lwd = 1,
             # jitter = .3,
             palette = c('gray20','#1f78b4','#a6cee3','#33a02c','#b2df8a')) +
tm_legend(legend.position = c(0,0),
            legend.bg.color = 'gray90',
            legend.frame = 'black') 
```

### DWL trend ridges
```{r}
library(ggridges)
png(filename = 'figs/trend_ridges.png',
    width = 2, height = 5.75, units = 'in', res = 300)
dwl_ridges <- dwl_all %>%
    filter(Trend!="No trend") %>%
  select(Hylak_id, value, Trend, year) %>%
  ungroup()

ggplot(dwl_ridges, aes(x = value, y = year, group = year)) +
  geom_density_ridges(
    data = filter(dwl_ridges, Trend == "Blue -> Green"),
    scale = 7,
    size = 0.25,
    rel_min_height = 0.01,
    fill = "#b2df8a",
    alpha = 0.4
  ) +
  geom_density_ridges(
    data = filter(dwl_ridges, Trend == "Green -> Blue"),
    scale = 7,
    size = 0.25,
    rel_min_height = 0.01,
    fill = "#a6cee3",
    alpha = 0.4
  ) +
  geom_density_ridges(
    data = filter(dwl_ridges, Trend == "Intensifying Blue"),
    scale = 7,
    size = 0.25,
    rel_min_height = 0.01,
    fill = "#1f78b4",
    alpha = 0.4
  ) +
  geom_density_ridges(
    data = filter(dwl_ridges, Trend == "Intensifying Green/Yellow"),
    scale = 7,
    size = 0.25,
    rel_min_height = 0.01,
    fill = "#33a02c",
    alpha = 0.4
  ) +
  theme_few(base_size = 9.5)+
  xlim(range(dwl_ridges$value)) + 
  facet_wrap( ~ Trend,nrow=4,scales="free_x")+
  theme(plot.margin = unit(c(0,0.1,0,0), "cm"))+
  scale_x_continuous(limits = c(470, 590), expand = c(0.01, 0)) +
  scale_y_reverse(breaks = c(seq(2020, 1984, -6))) +
  labs(x="Dominant wavelength (nm)",
       y="Year")
dev.off()

```


## DWL Trends -- why?
```{r}

#Create df for CART modeling

trends_df<-dwl_all %>%
  ungroup()%>%
  filter(Trend!="No trend") %>%
  # filter(Trend %in% c("Blue -> Green",
  #                     "Green -> Blue")) %>%
  select(Hylak_id, Trend) %>%
  # rename(sens.slope=slope) %>%
  mutate(Trend_simple=NA) %>%
    mutate(Trend_simple = replace(Trend_simple, Trend %in% c("Intensifying Blue"), 'Intensifying Blue'),
          Trend_simple = replace(Trend_simple, Trend %in% c("Intensifying Green/Yellow"), 'Intensifying Green/Yellow'),
          Trend_simple = replace(Trend_simple, Trend %in% c("Blue -> Green"), 'Blue -> Green'),
          Trend_simple = replace(Trend_simple, Trend %in% c("Green -> Blue"), 'Green -> Blue')) %>%
  # mutate(Trend_simple = replace(Trend_simple, Trend %in% c("Intensifying Blue","Green -> Blue"), 'Decreasing'),
  #        Trend_simple = replace(Trend_simple, Trend %in% c("Intensifying Green/Yellow","Blue -> Green"), 'Increasing')) %>%
  # mutate(Trend_simple = replace(Trend_simple, Trend %in% c("Green -> Blue"), 'Green -> Blue'),
         # Trend_simple = replace(Trend_simple, Trend %in% c("Blue -> Green"), 'Blue -> Green')) %>%
  mutate(Trend_simple = as.factor(as.character(Trend_simple))) %>%
  drop_na(Trend_simple) %>%
  distinct(Hylak_id,.keep_all = T) %>%
  inner_join(blue_green_2018) %>% #add LakeCat variables
  inner_join(prism_trends_wide) %>% #add PRISM variables
  inner_join(population_trends) %>% #add GLCP population variables
  inner_join(prism_trend_categories) %>% #prism trend categories
  mutate(log10LSA=log10(LSA),
         log10WALA=log10(WALA),
         log10ws_area=log10(ws_area),
         log10pop_sum=log10(pop_sum)) %>%
  select(-c(dWL,group,Trend,lake_connectivity)) %>%
  # mutate(Trend_simple = factor(Trend_simple, 
  #                         levels = c('Intensifying Blue',
  #                                    'Green -> Blue',
  #                                    'Intensifying Green/Yellow',
  #                                    'Blue -> Green'))) %>%
  # # select(-c(population_change,precip, contains("cv_"), contains("slope"), contains("perc_")))%>%
  select(Hylak_id, Trend_simple, res, log10ws_area, log10WALA, elev, meandepth, slope, log10LSA, log10pop_sum, slope_summer_tmean_degC, perc_barren,
         slope_winter_ppt_mm, ppt_trend_winter, temp_trend_summer, n_dep)
  # select(-c(air_temp,pop_sum)) %>%
  # select(-c(LSA,WALA,ws_area)) 
  # select(-c(LSA, maxdepth, slope_spring_tmean_degC)) %>% #dropping some highly correlated variables
  # select(-c(contains(c("perc_","cv_"))))

names(trends_df)
# droplevels(trends_df$Trend)
set.seed(4444)

train_d <- trends_df%>%
  sample_frac(0.7)

test_d <- trends_df %>%
  dplyr::filter(!Hylak_id %in% train_d$Hylak_id) %>%
  select(-Hylak_id) %>%
  mutate_if(is.numeric, round, digits=2) 
  # dplyr::select(-Hylak_id,-dWL, -group)

train_d <- train_d %>%
  select(-Hylak_id) %>%
  mutate_if(is.numeric, round, digits=2) 
  # dplyr::select(-Hylak_id,-dWL, -group)

##First check and see if there are any highly correlated variables. Maybe need to drop?
# library(GGally)
# ggpairs(train_d %>%select(where(is.numeric)))
# ggpairs(train_d %>%select(contains("slope")))


## Not run, but code that helped make decision about complexity parameter
# prune_mod <-caret::train(
#   Trend_simple ~., data = train_d, method = "rpart",
#   trControl = trainControl("boot", number = 100),
#   tuneLength = 100
#   )



cart_mod <- rpart(Trend_simple ~ ., data = train_d,
                  method = 'class',
                  cp = 0.03) # CP is a tuning knob for tree complexity.


test_d$guess <- predict(cart_mod, test_d, 'class')
cm <- conf_mat(test_d, Trend_simple,guess)
accuracy(test_d,Trend_simple,guess)

rpart.plot(cart_mod,
           type = 2, #2=split labels below node labels; but I like the look of 4 with labels on both connecting lines and no "yesno"
           extra = 2,#2 = class rate; 106 = prob. of 2nd class + percent of observations
           under = TRUE, #I kind of like the look of this better
           clip.right.labs = FALSE,
           branch = 0.3,
           # branch.type = 5, yesno=FALSE, #If you comment out type=4, I kind of like the look of this
           branch.col = "gray",
           # main="Factors that influence lake category",
           box.palette = list('#1f78b4','#a6cee3','#33a02c','#b2df8a'))
            # box.palette = list('#a6cee3','#b2df8a'))
hist(log10(trends_df$pop_sum), breaks=50)
hist(trends_df$slope_spring_tmean_degC, breaks=50)

## Create manually because the plot_confusion_matrix function is pissing me off
library(cvms)
conf_mat <- confusion_matrix(targets = test_d$Trend_simple,
                             predictions = test_d$guess)
table<-data.frame(conf_mat$`Confusion Matrix`)

plotTable <- table %>%
  group_by(Target) %>%
  mutate(prop = N/sum(N),
         prop = round(prop,2))

# png(filename = 'figs/bg_confusion_matrix_gg.png',
#     width = 6, height = 5,
#     units = 'in', res = 300)
temporal_conf_mat<-ggplot(data = plotTable,
       mapping = aes(x = Target, y = Prediction)) +
  # geom_tile(aes(fill=Pos_Green....Blue), color="black") +
  # geom_tile(aes(fill=Pos_Switch.to.Blue), color="black") +
    geom_tile(aes(fill=Pos_Decreasing), color="black") +
  # scale_x_discrete(expand = c(0, 0))+ #remove white space
  # scale_y_discrete(expand = c(0, 0))+ #remove white space
  geom_text(aes(label = paste0("n=",N)), vjust = .5,  alpha = 1, size=4) +
  geom_text(aes(label = paste0("prop.=",prop)), vjust = 2.0,  alpha = 1, size=3) +
  scale_fill_manual(values = c(TP = "#1f78b4", TN = "#33a02c",
                               FN = "white" , FP ="white")) +
  theme_few() +
  # xlim(rev(levels(table$Target)))+
  theme(legend.position="none")
# dev.off()
temporal_conf_mat


##GGPARTY? Another way
library(ggparty)
cart_mod_party<-as.party(cart_mod)
# plot(cart_mod_party)
temporal_tree_plot<-ggparty(cart_mod_party) +
  geom_edge(size=1, color="grey50") +
    # geom_node_label(aes(label = splitvar), ids = "inner") +
  geom_edge_label() +
  geom_node_splitvar() +
  geom_node_plot(gglist = list(geom_bar(aes(x = "", fill = Trend),
                                    position = position_fill()),#standardizes so each stack has constant height; plots proportions.
                               (scale_fill_manual(values=trendColors)),
                                                               (theme_few()),
                                # (scale_fill_manual(values=c('#b2df8a','#a6cee3'))),
                                #                                (theme_few()),
                               (theme(plot.margin = unit(c(0,0.2,0,0.2), "cm"),
                                axis.title.x=element_blank(),
                                axis.text.x=element_blank(),
                                axis.ticks.x=element_blank(),
                                legend.position="none")),
                               (scale_x_discrete(expand = c(0, 0))), #remove white space
                               # (scale_y_discrete(expand = c(0, 0))), #remove white space)
                               ylab("Proportion")),
                               shared_axis_labels = TRUE) +
    geom_node_label(aes(label = paste0("n=", nodesize)),
                  # fontface = "bold",
                  ids = "terminal",
                  size = 4, 
                  # nudge_y = 0.01,
                  nudge_x = 0.01)+
  theme(plot.margin = unit(c(0,0,0,0), "cm"))
  # labs(title="cp = 0.054; test/train split 70/30; accuracy = 0.615;
  #      predictors=all")
  # labs(title="cp = 0.08; test/train split 70/30; accuracy = 0.56;\n
  #      predictors=res, log10ws_area, log10WALA, elev, meandepth, slope,\n
  #      log10LSA, log10pop_sum, slope_summer_tmean_degC, perc_barren,\n
  #        slope_winter_ppt_mm, ppt_trend_winter, temp_trend_summer, n_dep")
temporal_tree_plot
temporal_tree_plot+inset_element(temporal_conf_mat, left = 0.67, bottom = 0.67, right = 1, top = 1, align_to = 'full')


#Combine
library(patchwork)

##Arrangement 1
png(filename = 'figs/temporal_plots.png',
width = 6, height = 7, units = 'in', res = 600)
C<-(spatial_hist+conf_matrix_plot)
(conf_matrix_plot/tree_plot)+ plot_layout(heights = c(0.3,1))+  plot_annotation(tag_levels = 'A')
#For top right alginment: inset_element(conf_matrix_plot, left = 0.67, bottom = 0.67, right = 1, top = 1, align_to = 'full')) 
dev.off()

# ##Arrangement 2
# B <- spatial_hist / conf_matrix_plot +   plot_layout(heights = c(2,1))
# tree_plot + B  +   plot_layout(widths = c(2,1)) +  plot_annotation(tag_levels = 'A')
# 
# ##Arrangement 3
# (spatial_hist / tree_plot + inset_element(conf_matrix_plot, left = 0.67, bottom = 0.67, right = 1, top = 1, align_to = 'full')) +
#    plot_layout(heights = c(0.5,1.5))+
#    plot_annotation(tag_levels = list(c('A', 'B'), '1'))

```

#### Random Forest
```{r}
library(randomForest)
trends_df<-dwl_all %>%
  ungroup()%>%
  filter(Trend!="No trend") %>%
  # filter(Trend %in% c("Blue -> Green",
  #                     "Green -> Blue")) %>%
  select(Hylak_id, Trend) %>%
  # rename(sens.slope=slope) %>%
  mutate(Trend_simple=NA) %>%
    mutate(Trend_simple = replace(Trend_simple, Trend %in% c("Intensifying Blue"), 'Intensifying Blue'),
          Trend_simple = replace(Trend_simple, Trend %in% c("Intensifying Green/Yellow"), 'Intensifying Green/Yellow'),
          Trend_simple = replace(Trend_simple, Trend %in% c("Blue -> Green"), 'Blue -> Green'),
          Trend_simple = replace(Trend_simple, Trend %in% c("Green -> Blue"), 'Green -> Blue')) %>%
  distinct(Hylak_id,.keep_all = T) %>%
  inner_join(blue_green_2018) %>% #add LakeCat variables
  inner_join(prism_trends_wide) %>% #add PRISM variables
  inner_join(population_trends) %>% #add GLCP population variables
  inner_join(prism_trend_categories) %>%  #prism trend categories
  select(-Trend) %>%
  rename(Trend=Trend_simple) %>%
  mutate(Trend = factor(
        Trend,
        levels = c(
          'Intensifying Blue',
          'Green -> Blue',
          'Intensifying Green/Yellow',
          'Blue -> Green'))) %>%
  select(-dWL, -group, -precip, -air_temp)
  # mutate(LSA=log10(LSA),
  #        WALA=log10(WALA),
  #        ws_area=log10(ws_area)) %>%
  # select(Hylak_id, Trend, res, WALA, slope, LSA, slope_summer_tmean_degC, perc_barren,
  #        slope_winter_ppt_mm, ppt_trend_winter, temp_trend_summer, no3_dep, nh3_dep)
set.seed(4444)

train_d <- trends_df %>%
  sample_frac(0.8) 

test_d <- trends_df %>%
  dplyr::filter(!Hylak_id %in% train_d$Hylak_id) %>%
  select(-Hylak_id) %>%
  mutate_if(is.numeric, round, digits=3)

train_d <- train_d %>%
  select(-Hylak_id) %>%
  mutate_if(is.numeric, round, digits=3) 

trControl <- trainControl(method = "cv",
    number = 10,
    search = "grid")

set.seed(1234)
# Run the model
rf_default <- train(Trend~.,
    data = train_d,
    method = "rf",
    metric = "Accuracy",
    trControl = trControl)
# Print the results
print(rf_default)

#Step 2) Search best mtry
tuneGrid <- expand.grid(.mtry = c(1: 10))
rf_mtry <- train(Trend~.,
    data = train_d,
    method = "rf",
    metric = "Accuracy",
    tuneGrid = tuneGrid,
    trControl = trControl,
    importance = TRUE,
    nodesize = 14,
    ntree = 300)
print(rf_mtry)
rf_mtry$bestTune$mtry #best value
best_mtry <- rf_mtry$bestTune$mtry 
best_mtry

#3) search the best maxnodes

store_maxnode <- list()
tuneGrid <- expand.grid(.mtry = best_mtry)
for (maxnodes in c(5: 15)) {
    set.seed(1234)
    rf_maxnode <- train(Trend~.,
        data = train_d,
        method = "rf",
        metric = "Accuracy",
        tuneGrid = tuneGrid,
        trControl = trControl,
        importance = TRUE,
        nodesize = 14,
        maxnodes = maxnodes,
        ntree = 300)
    current_iteration <- toString(maxnodes)
    store_maxnode[[current_iteration]] <- rf_maxnode
}
results_mtry <- resamples(store_maxnode)
summary(results_mtry)

#Step 4) Search the best ntrees
store_maxtrees <- list()
for (ntree in c(250, 300, 350, 400, 450, 500, 550, 600, 800, 1000, 2000)) {
    set.seed(5678)
    rf_maxtrees <- train(Trend~.,
        data = train_d,
        method = "rf",
        metric = "Accuracy",
        tuneGrid = tuneGrid,
        trControl = trControl,
        importance = TRUE,
        nodesize = 14,
        maxnodes = 20,
        ntree = ntree)
    key <- toString(ntree)
    store_maxtrees[[key]] <- rf_maxtrees
}
results_tree <- resamples(store_maxtrees)
summary(results_tree)

#Use the previous model summaries to build the final model
fit_rf <- randomForest(Trend~.,
    train_d,
    method = "rf",
    metric = "Accuracy",
    tuneGrid = tuneGrid,
    trControl = trControl,
    importance = TRUE,
    nodesize = 14,
    ntree = 400,
    maxnodes = 20)

# Step 5) Evaluate the model

prediction <-predict(fit_rf, test_d)
confusionMatrix(prediction, test_d$Trend)

#Step 6) Visualize Result
varImpPlot(fit_rf)
imp_df<-importance(fit_rf)
imp_df

library(pdp)           # for partial dependence plots
library(vip)           # for variable importance plots
vip(fit_rf, bar = FALSE, horizontal = FALSE, size = 1.5) 


# plot(trends_df$cv_summer_tmean_degC, 
#      trends_df$slope_summer_tmean_degC)
```

##### Distribution of top predictors
```{r}
trendColors2 <- c(
  'No trend' = 'black',
  'Intensifying Blue' = '#1f78b4',
  'Green -> Blue' = '#a6cee3',
  'Intensifying Green/Yellow' = '#33a02c',
  'Blue -> Green' = '#b2df8a'
)

mu <- dwl_all %>%
  select(Hylak_id, Trend) %>%
  distinct(Hylak_id, .keep_all = T) %>%
  inner_join(blue_green_2018) %>% #add LakeCat variables
  inner_join(prism_trends_wide) %>% #add PRISM variables
  inner_join(population_trends) %>% #add GLCP population variables
  inner_join(prism_trend_categories) %>% #prism trend categories
  ungroup() %>%
  select(Trend,
         elev,
         cv_summer_tmean_degC,
         slope_spring_tmean_degC,
         slope) %>%
  pivot_longer(-Trend) %>%
  group_by(Trend, name) %>%
  summarize(grp.mean = mean(value, na.rm = TRUE))

dwl_all %>%
  select(Hylak_id, Trend) %>%
  distinct(Hylak_id, .keep_all = T) %>%
  inner_join(blue_green_2018) %>% #add LakeCat variables
  inner_join(prism_trends_wide) %>% #add PRISM variables
  inner_join(population_trends) %>% #add GLCP population variables
  inner_join(prism_trend_categories) %>% #prism trend categories
  ungroup() %>%
  select(Trend,
         elev,
         cv_summer_tmean_degC,
         slope_spring_tmean_degC,
         slope) %>%
  pivot_longer(-Trend) %>%
  ggplot(aes(x = value, group = Trend)) +
  geom_density(aes(fill = Trend), alpha = 0.4) +
  geom_vline(aes(xintercept = grp.mean, color = Trend),
             data = mu,
             linetype = "dashed") +
  scale_color_manual(values = trendColors2) +
  scale_fill_manual(values = trendColors) +
  # facet_wrap(name~., scales="free", nrow=5, ncol=4)
  facet_wrap(
    Trend ~ name,
    scales = "free",
    ncol = 4,
    strip.position = "right"
  )

#Elev plot
A<-dwl_all %>%
  select(Hylak_id, Trend) %>%
  distinct(Hylak_id, .keep_all = T) %>%
  inner_join(blue_green_2018) %>% #add LakeCat variables
  inner_join(prism_trends_wide) %>% #add PRISM variables
  inner_join(population_trends) %>% #add GLCP population variables
  inner_join(prism_trend_categories) %>% #prism trend categories
  ungroup() %>%
  select(Trend,
         elev,
         cv_summer_tmean_degC,
         slope_spring_tmean_degC,
         slope) %>%
  pivot_longer(-Trend) %>%
  filter(name=="elev")%>%
  ggplot(aes(x = value, group = Trend)) +
  # geom_density(aes(fill = Trend), alpha = 0.4) +
    geom_freqpoly(aes(color=Trend),bins = 10, size = 1) + 
  geom_vline(aes(xintercept = grp.mean, color = Trend),
             data = mu%>%
  filter(name=="elev"),
             linetype = "dashed") +
  scale_color_manual(values = trendColors2) +
  scale_fill_manual(values = trendColors) +
  facet_wrap(
    Trend ~ .,
    scales = "free_y",
    ncol = 1,
    strip.position = "right"
  )+
    theme_few()+
  theme(strip.text = element_blank(),
        legend.position = "none")+
  labs(x="Elevation (m)")
#cv_summer_tmean_degC plot
B<-dwl_all %>%
  select(Hylak_id, Trend) %>%
  distinct(Hylak_id, .keep_all = T) %>%
  inner_join(blue_green_2018) %>% #add LakeCat variables
  inner_join(prism_trends_wide) %>% #add PRISM variables
  inner_join(population_trends) %>% #add GLCP population variables
  inner_join(prism_trend_categories) %>% #prism trend categories
  ungroup() %>%
  select(Trend,cv_summer_tmean_degC) %>%
  pivot_longer(-Trend) %>%
  ggplot(aes(x = value, group = Trend)) +
  # geom_density(aes(fill = Trend), alpha = 0.4) +
    geom_freqpoly(aes(color=Trend),bins = 10, size = 1) + 
  geom_vline(aes(xintercept = grp.mean, color = Trend),
             data = mu%>%
  filter(name=="cv_summer_tmean_degC"),
             linetype = "dashed") +
  scale_color_manual(values = trendColors2) +
  scale_fill_manual(values = trendColors) +
  facet_wrap(
    Trend ~ .,
    scales = "free_y",
    ncol = 1,
    strip.position = "right"
  )+
  theme_few()+
  theme(strip.text = element_blank(),
        legend.position = "none")+
  labs(x="C.V. summer\ntemp (°C)")
#slope_spring_tmean_degC plot
C<-dwl_all %>%
  select(Hylak_id, Trend) %>%
  distinct(Hylak_id, .keep_all = T) %>%
  inner_join(blue_green_2018) %>% #add LakeCat variables
  inner_join(prism_trends_wide) %>% #add PRISM variables
  inner_join(population_trends) %>% #add GLCP population variables
  inner_join(prism_trend_categories) %>% #prism trend categories
  ungroup() %>%
  select(Trend,slope_spring_tmean_degC) %>%
  pivot_longer(-Trend) %>%
  ggplot(aes(x = value, group = Trend)) +
  # geom_density(aes(fill = Trend), alpha = 0.4) +
    geom_freqpoly(aes(color=Trend),bins = 10, size = 1) + 
  geom_vline(aes(xintercept = grp.mean, color = Trend),
             data = mu%>%
  filter(name=="slope_spring_tmean_degC"),
             linetype = "dashed") +
  scale_color_manual(values = trendColors2) +
  scale_fill_manual(values = trendColors) +
  facet_wrap(
    Trend ~ .,
    scales = "free_y",
    ncol = 1,
    strip.position = "right"
  )+
  theme_few()+
  theme(strip.text = element_blank(),
        legend.position = "none")+
  labs(x="Slope \nspring temp (°C)")
#slope_spring_tmean_degC plot
D<-dwl_all %>%
  select(Hylak_id, Trend) %>%
  distinct(Hylak_id, .keep_all = T) %>%
  inner_join(blue_green_2018) %>% #add LakeCat variables
  inner_join(prism_trends_wide) %>% #add PRISM variables
  inner_join(population_trends) %>% #add GLCP population variables
  inner_join(prism_trend_categories) %>% #prism trend categories
  ungroup() %>%
  select(Trend,slope) %>%
  pivot_longer(-Trend) %>%
  ggplot(aes(x = value, group = Trend)) +
  # geom_density(aes(fill = Trend), alpha = 0.4) +
  geom_freqpoly(aes(color=Trend),bins = 10, size = 1) + 
  geom_vline(aes(xintercept = grp.mean, color = Trend),
             data = mu%>%
  filter(name=="slope"),
             linetype = "dashed") +
  scale_color_manual(values = trendColors2) +
  scale_fill_manual(values = trendColors) +
  facet_wrap(
    Trend ~ .,
    scales = "free_y",
    ncol = 1,
    strip.position = "right"
  )+
  theme_few()+
  theme(legend.position = "none")+
  labs(x="Mean WS slope")
A|B|C|D 
```


### Explore trends
```{r}
head(trends_df)

explore <- dwl_all %>%
  ungroup()%>%
  # filter(Trend!="No trend") %>%
  # filter(Trend %in% c("Blue -> Green",
  #                     "Green -> Blue")) %>%
  select(Hylak_id, Trend, slope) %>%
  rename(sens.slope=slope) %>%
  # mutate(Trend_simple=NA) %>%
  # mutate(Trend_simple = replace(Trend_simple, Trend %in% c("Intensifying Blue","Green -> Blue"), 'Bluer'),
  #        Trend_simple = replace(Trend_simple, Trend %in% c("Intensifying Green/Yellow","Blue -> Green"), 'Greener')) %>%
  distinct(Hylak_id,.keep_all = T) %>%
  inner_join(blue_green_2018) %>% #add LakeCat variables
  inner_join(prism_trends_wide) %>% #add PRISM variables
  inner_join(population_trends) %>% #add GLCP population variables
  inner_join(prism_trend_categories) #prism trend categories
  # select(-c(air_temp,precip,pop_sum)) %>%
  # select(-c(contains(c("perc_","cv_"))))
# head(explore)
str(explore)

explore %>%
  ggplot(aes(x=slope,y=population_change,fill=Trend))+
  geom_point(shape=21)+
  scale_fill_manual(values=trendColors)+
  geom_hline(yintercept=-94) #the cutoff for trending blue in one of CART model runs


#First tree node -- if winter ppt is not changing, the lake is greening (about 6 sites)
# But if the slope of winter ppt is between -0.055 to 0.34, lake most likely getting blue
explore %>%
  ggplot(aes(x=slope,y=slope_winter_ppt_mm,fill=Trend))+
  geom_point(shape=21)+
  scale_fill_manual(values=trendColors)+
  geom_hline(yintercept=0.335)+ #the cutoff for trending blue in one of CART model runs
  geom_hline(yintercept=-0.055) #the cutoff for trending blue in one of CART model runs

#First tree node -- if winter ppt is increasing, and summer temperature is NOT increasing
#Then lake most likely intensifying blue
explore %>%
  filter(elev<2617.32) %>%
  filter(Trend!="No trend") %>%
  ggplot(aes(x=slope_summer_tmean_degC,y=slope_spring_ppt_mm,fill=Trend))+
  geom_point(shape=21,size=3)+
  scale_fill_manual(values=trendColors)+
  geom_hline(yintercept=0.06)+ 
  geom_vline(xintercept=0.035) 

explore %>%
  filter(elev<2617.32) %>%
  filter(Trend!="No trend") %>%
  ggplot(aes(x=elev,y=perc_barren,fill=Trend))+
  geom_point(shape=21,size=3)+
  scale_fill_manual(values=trendColors)+
  geom_hline(yintercept=0.06)+ 
  geom_vline(xintercept=0.035) 

##Code borrowed from Simon Topp's 2021 ERL paper
#Look at the distribution of clarity change across in-network and out-of-network lakes, no
ggplot(explore, aes(x = sens.slope)) +
  geom_density(alpha = .4, aes(fill = factor(Trend)))+
    scale_fill_manual(values=trendColors)

ggplot(explore %>%
           filter(Trend!="No trend"), aes(x = elev, color=Trend)) +
  # geom_histogram(aes(x=elev, y = ..density.., fill=Trend),
  #                color = 'black',bins = 50) + 
  # geom_density(aes(x=elev)) + 
  geom_freqpoly(bins = 20, size = 1) + 
  scale_color_manual(values=trendColors)+
  facet_wrap(~Trend,nrow=4,scales="free_y")+
  geom_vline(xintercept=2617.32)+
  theme(legend.position="none")


explore %>%
  select(Hylak_id, Trend, sens.slope, slope, n_dep, WALA, LSA, ws_area) %>%
  pivot_longer(-c(1:3)) %>%
  # filter(name=="n_dep") %>%
  ggplot(aes(x = value)) +
  geom_density(alpha = .4, aes(fill = factor(Trend)))+
  scale_fill_manual(values=trendColors)+
  facet_wrap(name~., scales="free")

hist(explore$n_dep)

###################################################
# Look at reservoirs vs natural lakes
###################################################
ggplot(explore, aes(x = res, y = sens.slope, group = res))  +
  geom_violin() + 
  geom_boxplot(width = .1, fill = 'grey60') +
  geom_hline(yintercept = 0, color = 'red') +
  facet_wrap(~Trend)+
  # scale_fill_viridis_c('Number of\nLakes', option = 'plasma', end = .8, trans = 'log10') +
  # coord_cartesian(ylim = c(-5,5))+
  labs(x = 'Lake Type', y = 'Slope Distribution (dwl/year)', title = 'Slope Distribution by lake Type') +
  theme_few()

#No differences
wilcox.test(explore$sens.slope[explore$res == 'NL' & explore$Trend == 'Intensifying Green/Yellow'],
            explore$sens.slope[explore$res == 'RSVR' & explore$Trend == 'Intensifying Green/Yellow'], conf.int = T)
wilcox.test(explore$sens.slope[explore$res == 'NL' & explore$Trend == 'Intensifying Blue'],
            explore$sens.slope[explore$res == 'RSVR' & explore$Trend == 'Intensifying Blue'], conf.int = T)


ggplot(explore, aes(x = temp_trend_summer, y = sens.slope, group = temp_trend_summer))  +
  geom_violin() + 
  geom_boxplot(width = .1, fill = 'grey60') +
  geom_hline(yintercept = 0, color = 'red') +
  facet_wrap(~Trend)+
  # scale_fill_viridis_c('Number of\nLakes', option = 'plasma', end = .8, trans = 'log10') +
  # coord_cartesian(ylim = c(-5,5))+
  labs(x = 'Lake Type', y = 'Slope Distribution (dwl/year)', title = 'Slope Distribution by lake Type') +
  theme_few()

wilcox.test(explore$sens.slope[explore$temp_trend_summer == 'No trend' & explore$Trend == 'Intensifying Blue'],
            explore$sens.slope[explore$temp_trend_summer == 'warmer' & explore$Trend == 'Intensifying Blue'], conf.int = T)
#There are some differences but honestly kind of hard to interpret. In areas with warming summer, the intensifying blue slope is lower?

explore %>%
  mutate(Size.Group = cut(area, breaks = c(0,1,10,100,2000), labels = c('<1','1-10','10-100','>100'))) %>%
  ggplot(aes(x = Size.Group, y = abs(sens.slope), group = Size.Group, fill=Trend))  +
  # geom_violin() + 
  geom_jitter(shape=21, alpha=0.9, width=0.2) +
  geom_boxplot(width = .1, outlier.shape=NA) +
  geom_hline(yintercept = 0, color = 'red') +
  facet_wrap(~Trend, ncol=5, scales="free_y")+
  scale_fill_manual(values=trendColors)+
  labs(x = 'Lake Type', y = 'Slope Distribution (dwl/year)', title = 'Slope Distribution by lake Type') +
  theme_few()

#Within each trend category, RSVRs have steeper slopes than natural lakes
explore %>%
  ggplot(aes(x = res, y = sens.slope, group = res, fill=Trend))  +
  # geom_violin() + 
  geom_boxplot(width = .3, outlier.shape=NA) +
    geom_jitter(shape=21, alpha=0.9, width=0.2) +
  geom_hline(yintercept = 0, color = 'red') +
  facet_wrap(~Trend, ncol=5, scales="free_y")+
  scale_fill_manual(values=trendColors)+
  labs(x = 'Lake Type', y = 'Slope Distribution (dwl/year)', title = 'Slope Distribution by lake Type') +
  theme_few()

explore %>%
  ggplot(aes(x = temp_trend_summer, y = slope_summer_tmean_degC, group = temp_trend_summer, fill=Trend))  +
  # geom_violin() + 
  geom_jitter(shape=21, alpha=0.9, width=0.2) +
  geom_boxplot(width = .1, outlier.shape=NA) +
  geom_hline(yintercept = 0, color = 'red') +
  facet_wrap(~Trend, ncol=5)+
  scale_fill_manual(values=trendColors)+
  labs(x = 'Lake Type', y = 'Summer Temp Slope Distribution (deg C/year)', title = 'Slope Distribution by lake Type',
       subtitle='In all trend categories, there are a sizable number of lakes that experience summer warming') +
  theme_few()

explore %>%
  ggplot(aes(x = temp_trend_summer, y = sens.slope, group = temp_trend_summer, fill=Trend))  +
  # geom_violin() + 
  geom_jitter(shape=21, alpha=0.9, width=0.2) +
  geom_boxplot(width = .1, outlier.shape=NA) +
  geom_hline(yintercept = 0, color = 'red') +
  facet_wrap(~Trend, ncol=5)+
  scale_fill_manual(values=trendColors)+
  labs(x = 'Summer warming?', y = 'Slope Distribution (dwl/year)', title = 'Slope Distribution by lake Type',
       subtitle="But the slope of the color change isn't different between lakes experiencing summer warming or not") +
  theme_few()

explore %>%
  ggplot(aes(x = ppt_trend_winter, y = sens.slope, group = ppt_trend_winter, fill=Trend))  +
  # geom_violin() + 
  geom_jitter(shape=21, alpha=0.9, width=0.2) +
  geom_boxplot(width = .1, outlier.shape=NA) +
  geom_hline(yintercept = 0, color = 'red') +
  facet_wrap(~Trend, ncol=5)+
  scale_fill_manual(values=trendColors)+
  labs(x = 'Winter wetter?', y = 'Slope Distribution (dwl/year)', title = 'Slope Distribution by lake Type',
       subtitle="But the slope of the color change isn't different between lakes experiencing summer warming or not") +
  theme_few()

```